
const HEMSAMARITEN_WCF_SERVICE_BASE_URL ="http://localhost:8525/HemsamaritenWCFService/";
const HEMSAMARITEN_TELLSTICK = HEMSAMARITEN_WCF_SERVICE_BASE_URL + "tellstick/";
const HEMSAMARITEN_MEDIA = HEMSAMARITEN_WCF_SERVICE_BASE_URL + "media/";
